language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t azarelia/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true azarelia/docker-react npm run test